apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: runasroot
  securityContext:
    runAsUser: 0      
  containers:
  - name: nginx
    image: nexus01.centrala.kaczmarski.pl:8082/docker.io/nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html/
        name: index
  volumes:
    - name: index
      configMap: 
        name: index