apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: nexus01.centrala.kaczmarski.pl:8082/docker.io/redis:latest
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    securityContext:
      runAsUser: 0
      privileged: true    
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /usr/local/etc/redis/
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: example-redis-config
        items:
        - key: redis-config
          path: redis.conf