apiVersion: batch/v1
kind: Job
metadata:
  name: rabbit-perf
  namespace: sandbox-h-cudniewicz
spec:
  selector: {}
  template:
    metadata:
      name: pi
    spec:
      containers:
        - name: perftest
          image: pivotalrabbitmq/perf-test:latest        
          args: ["-h","amqp://kg_svc1_publisher:alamakota123@rabbit-amqp"]
      restartPolicy: Never
