apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-roll
spec:
  selector:
    matchLabels:
      app: hello-roll
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 1 
      intervalSeconds: 1 
      timeoutSeconds: 120 
      maxSurge: "20%" 
      maxUnavailable: "10%" 
      pre: {} 
      post: {}
  template:
    metadata:
      labels:
        app: hello-roll
    spec:
      containers:
      - name: hello-roll
        image: paulbouwer/hello-kubernetes:1.5
        resources:
          limits:
            memory: "15Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
