apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello
  name: hello
  namespace: sandbox-p-ryttel
spec:
  containers:
  - image: paulbouwer/hello-kubernetes:1
    name: hello
    ports:
      - containerPort: 8080
  imagePullSecrets:
  - name: regcred
