apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello
  name: hello
spec:
  containers:
  - image: paulbouwer/hello-kubernetes:1
    name: hello
    ports:
      - containerPort: 8080
        name: http
  imagePullSecrets:
  - name: regcred
