apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: paulbouwer/hello-kubernetes:1
    name: hello
    ports:
      - containerPort: 80
  imagePullSecrets:
  - name: regcred
