apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyeXR0ZWxwIiwicGFzc3dvcmQiOiJwMmVudDRpdTNtIiwiZW1haWwiOiJwYXdlbC5yeXR0ZWxAZ21haWwuY29tIiwiYXV0aCI6ImNubDBkR1ZzY0Rwd01tVnVkRFJwZFROdCJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2022-09-16T11:20:55Z"
  name: regcred
  namespace: k8s-tutorial
  resourceVersion: "171995474"
  uid: 50cc8750-19e8-4ec1-a7d8-1a71b09f9936
type: kubernetes.io/dockerconfigjson