{{- $fullName := include "tutor-osh.fullname" . -}}
{{- range .Values.names}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ . | replace "." "-" }}-admin-{{ $fullName }}-{{ . | replace "." "-" }}
  namespace: {{ $fullName }}-{{ . | replace "." "-" }}
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ . | replace "." "-" }}-clusterreader
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-anyuid
  namespace: {{ $fullName }}-{{ . | replace "." "-" }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ $fullName }}-{{ . | replace "." "-" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
{{- end}}